### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by kevindelsh** [leon-good-life/developer-cheatsheets#14]
I found a spelling error in [es6](https://github.com/leon-good-life/developer-cheatsheets/tree/master/es6) and would like to make a pull request.

**Comment by leon-good-life** [comment]
@kevindelsh I would be very happy to review and merge your pull request.

**Comment by kevindelsh** [comment]
@leon-good-life Just made two minor edits.

**Comment by leon-good-life** [comment]
@kevindelsh Thanks a lot
