### ISSUE TITLE
First I love the way that you explaine a front end techonoligies with a great example....Second I would love to see CheatSheet of Angular

### ISSUE THREAD

**Issue by youssefsiyed** [leon-good-life/developer-cheatsheets#3]
I would Love to see An Angular CheatSheet Article... Thank You

**Comment by dalerasrorov-eb** [comment]
Great title

**Comment by leon-good-life** [comment]
Thank You @youssefsiyed , I happy you liked it.
I have plans to make also an Angular Cheatsheet,
And I will make it easy for developers to add examples to the cheatsheet.
